-- Đăng nhập bằng SYS
-- Tạo user quản trị hệ thống ứng dụng
CREATE USER C##ADMIN IDENTIFIED BY 123456 CONTAINER=ALL;

-- Cấp quyền cơ bản
GRANT CONNECT, RESOURCE TO C##ADMIN CONTAINER=ALL;

-- Cấp quyền quản lý user
GRANT CREATE USER TO C##ADMIN CONTAINER=ALL;
GRANT DROP USER TO C##ADMIN CONTAINER=ALL;
GRANT ALTER USER TO C##ADMIN CONTAINER=ALL;

-- Cấp quyền quản lý role (phải do SYS cấp)
GRANT CREATE ROLE TO C##ADMIN CONTAINER=ALL;
GRANT DROP ANY ROLE TO C##ADMIN CONTAINER=ALL;
GRANT GRANT ANY ROLE TO C##ADMIN CONTAINER=ALL;

-- Cấp quyền cấp bất kỳ quyền nào
GRANT GRANT ANY PRIVILEGE TO C##ADMIN CONTAINER=ALL;

-- Cấp quyền xem các user/role/table từ hệ thống
GRANT SELECT_CATALOG_ROLE TO C##ADMIN CONTAINER=ALL;

-- Cấp quyền sử dụng tablespace
GRANT UNLIMITED TABLESPACE TO C##ADMIN CONTAINER=ALL;

GRANT CREATE SESSION TO C##ADMIN CONTAINER=ALL;

GRANT SELECT ANY TABLE TO C##ADMIN CONTAINER=ALL;
GRANT INSERT ANY TABLE TO C##ADMIN CONTAINER=ALL;
GRANT DELETE ANY TABLE TO C##ADMIN CONTAINER=ALL;
GRANT UPDATE ANY TABLE TO C##ADMIN CONTAINER=ALL;

SELECT * 
FROM dba_sys_privs 
WHERE grantee = 'C##ADMIN' 
  AND privilege = 'CREATE USER';

GRANT INHERIT ANY PRIVILEGES TO C##ADMIN CONTAINER=ALL;

GRANT SELECT ON dba_roles TO C##ADMIN CONTAINER=ALL;
GRANT SELECT ON dba_data_files TO C##ADMIN CONTAINER=ALL;

-- Cấp quyền quản lý tablespace
GRANT CREATE TABLESPACE TO C##ADMIN CONTAINER=ALL;
GRANT ALTER TABLESPACE TO C##ADMIN CONTAINER=ALL;
GRANT DROP TABLESPACE TO C##ADMIN CONTAINER=ALL;
GRANT MANAGE TABLESPACE TO C##ADMIN CONTAINER=ALL;

-- Cấp quyền quản lý audit
GRANT AUDIT SYSTEM TO C##ADMIN CONTAINER=ALL;
GRANT AUDIT ANY TO C##ADMIN CONTAINER=ALL;

-- Cấp quyền quản lý session
GRANT CREATE SESSION TO C##ADMIN CONTAINER=ALL;
GRANT ALTER SESSION TO C##ADMIN CONTAINER=ALL;

-- Cấp quyền quản lý procedure
GRANT CREATE PROCEDURE TO C##ADMIN CONTAINER=ALL;
GRANT EXECUTE ANY PROCEDURE TO C##ADMIN CONTAINER=ALL;

-- Cấp quyền quản lý table
GRANT CREATE TABLE TO C##ADMIN CONTAINER=ALL;
GRANT ALTER ANY TABLE TO C##ADMIN CONTAINER=ALL;
GRANT DROP ANY TABLE TO C##ADMIN CONTAINER=ALL;

-- Cấp quyền quản lý sequence
GRANT CREATE SEQUENCE TO C##ADMIN CONTAINER=ALL;
GRANT ALTER ANY SEQUENCE TO C##ADMIN CONTAINER=ALL;
GRANT DROP ANY SEQUENCE TO C##ADMIN CONTAINER=ALL;

-- Cấp quyền quản lý view
GRANT CREATE VIEW TO C##ADMIN CONTAINER=ALL;
GRANT DROP ANY VIEW TO C##ADMIN CONTAINER=ALL;

-- Cấp quyền quản lý trigger
GRANT CREATE TRIGGER TO C##ADMIN CONTAINER=ALL;
GRANT ALTER ANY TRIGGER TO C##ADMIN CONTAINER=ALL;
GRANT DROP ANY TRIGGER TO C##ADMIN CONTAINER=ALL;

-- Cấp quyền quản lý index
GRANT CREATE ANY INDEX TO C##ADMIN CONTAINER=ALL;
GRANT ALTER ANY INDEX TO C##ADMIN CONTAINER=ALL;
GRANT DROP ANY INDEX TO C##ADMIN CONTAINER=ALL;

-- Cấp quyền quản lý synonym
GRANT CREATE SYNONYM TO C##ADMIN CONTAINER=ALL;
GRANT DROP ANY SYNONYM TO C##ADMIN CONTAINER=ALL;

-- Cấp quyền quản lý public synonym
GRANT CREATE PUBLIC SYNONYM TO C##ADMIN CONTAINER=ALL;
GRANT DROP PUBLIC SYNONYM TO C##ADMIN CONTAINER=ALL;

-- Cấp quyền quản lý database link
GRANT CREATE DATABASE LINK TO C##ADMIN CONTAINER=ALL;
GRANT DROP PUBLIC DATABASE LINK TO C##ADMIN CONTAINER=ALL;

-- Cấp quyền quản lý job
GRANT CREATE JOB TO C##ADMIN CONTAINER=ALL;
GRANT EXECUTE ANY PROGRAM TO C##ADMIN CONTAINER=ALL;

-- Cấp quyền quản lý materialized view
GRANT CREATE MATERIALIZED VIEW TO C##ADMIN CONTAINER=ALL;
GRANT ALTER ANY MATERIALIZED VIEW TO C##ADMIN CONTAINER=ALL;
GRANT DROP ANY MATERIALIZED VIEW TO C##ADMIN CONTAINER=ALL;

-- Cấp quyền quản lý dimension
GRANT CREATE DIMENSION TO C##ADMIN CONTAINER=ALL;
GRANT ALTER ANY DIMENSION TO C##ADMIN CONTAINER=ALL;
GRANT DROP ANY DIMENSION TO C##ADMIN CONTAINER=ALL;

-- Cấp quyền quản lý type
GRANT CREATE TYPE TO C##ADMIN CONTAINER=ALL;
GRANT ALTER ANY TYPE TO C##ADMIN CONTAINER=ALL;
GRANT DROP ANY TYPE TO C##ADMIN CONTAINER=ALL;

-- Cấp quyền quản lý operator
GRANT CREATE OPERATOR TO C##ADMIN CONTAINER=ALL;
GRANT ALTER ANY OPERATOR TO C##ADMIN CONTAINER=ALL;
GRANT DROP ANY OPERATOR TO C##ADMIN CONTAINER=ALL;

-- Cấp quyền quản lý indextype
GRANT CREATE INDEXTYPE TO C##ADMIN CONTAINER=ALL;
GRANT ALTER ANY INDEXTYPE TO C##ADMIN CONTAINER=ALL;
GRANT DROP ANY INDEXTYPE TO C##ADMIN CONTAINER=ALL;

-- Cấp quyền quản lý library
GRANT CREATE LIBRARY TO C##ADMIN CONTAINER=ALL;
GRANT ALTER ANY LIBRARY TO C##ADMIN CONTAINER=ALL;
GRANT DROP ANY LIBRARY TO C##ADMIN CONTAINER=ALL;

-- Cấp quyền quản lý directory
GRANT CREATE ANY DIRECTORY TO C##ADMIN CONTAINER=ALL;
GRANT DROP ANY DIRECTORY TO C##ADMIN CONTAINER=ALL;

-- Cấp quyền quản lý profile
GRANT CREATE PROFILE TO C##ADMIN CONTAINER=ALL;
GRANT ALTER PROFILE TO C##ADMIN CONTAINER=ALL;
GRANT DROP PROFILE TO C##ADMIN CONTAINER=ALL;

-- Cấp quyền quản lý tablespace
GRANT CREATE TABLESPACE TO C##ADMIN CONTAINER=ALL;
GRANT ALTER TABLESPACE TO C##ADMIN CONTAINER=ALL;
GRANT DROP TABLESPACE TO C##ADMIN CONTAINER=ALL;
GRANT MANAGE TABLESPACE TO C##ADMIN CONTAINER=ALL;

-- Cấp quyền quản lý rollback segment
GRANT CREATE ROLLBACK SEGMENT TO C##ADMIN CONTAINER=ALL;
GRANT ALTER ROLLBACK SEGMENT TO C##ADMIN CONTAINER=ALL;
GRANT DROP ROLLBACK SEGMENT TO C##ADMIN CONTAINER=ALL;

-- Cấp quyền quản lý cluster
GRANT CREATE CLUSTER TO C##ADMIN CONTAINER=ALL;
GRANT ALTER ANY CLUSTER TO C##ADMIN CONTAINER=ALL;
GRANT DROP ANY CLUSTER TO C##ADMIN CONTAINER=ALL;

-- Cấp quyền quản lý database
GRANT ALTER DATABASE TO C##ADMIN CONTAINER=ALL;
GRANT ALTER SYSTEM TO C##ADMIN CONTAINER=ALL;

-- Cấp quyền quản lý session
GRANT CREATE SESSION TO C##ADMIN CONTAINER=ALL;
GRANT ALTER SESSION TO C##ADMIN CONTAINER=ALL;

-- Cấp quyền quản lý audit
GRANT AUDIT SYSTEM TO C##ADMIN CONTAINER=ALL;
GRANT AUDIT ANY TO C##ADMIN CONTAINER=ALL;

-- Cấp quyền quản lý system
GRANT ALTER SYSTEM TO C##ADMIN CONTAINER=ALL;
GRANT ALTER DATABASE TO C##ADMIN CONTAINER=ALL;

-- Cấp quyền quản lý resource
GRANT UNLIMITED TABLESPACE TO C##ADMIN CONTAINER=ALL;
GRANT RESOURCE TO C##ADMIN CONTAINER=ALL;
