--XÓA CÁC RÀNG BUỘC KHÓA NGOẠI
ALTER TABLE DANGKY DROP CONSTRAINT FK_DK_SV;
ALTER TABLE DANGKY DROP CONSTRAINT FK_DK_MM;
ALTER TABLE MOMON DROP CONSTRAINT FK_MM_HP;
ALTER TABLE MOMON DROP CONSTRAINT FK_MM_GV;
ALTER TABLE HOCPHAN DROP CONSTRAINT FK_HP_DV;
ALTER TABLE SINHVIEN DROP CONSTRAINT FK_SV_KHOA;
ALTER TABLE NHANVIEN DROP CONSTRAINT FK_NV_DV;
ALTER TABLE DONVI DROP CONSTRAINT FK_TRGDV;

--XÓA CÁC BẢNG CŨ
DROP TABLE DANGKY;
DROP TABLE MOMON;
DROP TABLE HOCPHAN;
DROP TABLE SINHVIEN;
DROP TABLE NHANVIEN;
DROP TABLE DONVI;

--TẠO BẢNG DONVI
CREATE TABLE DONVI (
    MADV    NVARCHAR2(10) PRIMARY KEY,
    TENDV   NVARCHAR2(100) NOT NULL,
    LOAIDV  NVARCHAR2(10) CHECK (LOAIDV IN ('Khoa', N'Phòng')),
    TRGDV   VARCHAR2(10)
);

--TẠO BẢNG NHANVIEN
CREATE TABLE NHANVIEN (
    MANLD   VARCHAR2(10) PRIMARY KEY,
    HOTEN   NVARCHAR2(100) NOT NULL,
    PHAI    NVARCHAR2(5),
    NGSINH  DATE,
    LUONG   NUMBER(10, 2),
    PHUCAP  NUMBER(10, 2),
    DT      VARCHAR2(15),
    VAITRO  NVARCHAR2(50) CHECK (VAITRO IN ('NVCB', 'GV', N'NV PĐT', 'NV PKT', 'NV TCHC', 'NV CTSV', N'TRGĐV')),
    MADV    VARCHAR2(10)
);

--TẠO BẢNG SINHVIEN
CREATE TABLE SINHVIEN (
    MASV       VARCHAR2(10) PRIMARY KEY,
    HOTEN      NVARCHAR2(100) NOT NULL,
    PHAI       NVARCHAR2(5),
    NGSINH     DATE,
    DCHI       NVARCHAR2(200),
    DT         VARCHAR2(15),
    KHOA       VARCHAR2(10),
    TINHTRANG  NVARCHAR2(20) CHECK (TINHTRANG IN (N'đang học', N'nghỉ học', N'bảo lưu'))
);

--TẠO BẢNG HOCPHAN
CREATE TABLE HOCPHAN (
    MAHP   VARCHAR2(10) PRIMARY KEY,
    TENHP  NVARCHAR2(100) NOT NULL,
    SOTC   NUMBER(2),
    STLT   NUMBER(3),
    STTH   NUMBER(3),
    MADV   VARCHAR2(10)
);

--TẠO BẢNG MOMON
CREATE TABLE MOMON (
    MAMM   VARCHAR2(10) PRIMARY KEY,
    MAHP   VARCHAR2(10),
    MAGV   VARCHAR2(10),
    HK     NUMBER(1) CHECK (HK IN (1, 2, 3)),
    NAM    NUMBER(4) CHECK (NAM >= 2000)
);

--TẠO BẢNG DANGKY
CREATE TABLE DANGKY (
    MASV     VARCHAR2(10),
    MAMM     VARCHAR2(10),
    DIEMTH   NUMBER(4, 2),
    DIEMQT   NUMBER(4, 2),
    DIEMCK   NUMBER(4, 2),
    DIEMTK   NUMBER(4, 2),
    PRIMARY KEY (MASV, MAMM)
);

--THÊM CÁC KHÓA NGOẠI
ALTER TABLE DONVI
ADD CONSTRAINT FK_TRGDV FOREIGN KEY (TRGDV) REFERENCES NHANVIEN(MANLD);

ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_NV_DV FOREIGN KEY (MADV) REFERENCES DONVI(MADV);

ALTER TABLE SINHVIEN
ADD CONSTRAINT FK_SV_KHOA FOREIGN KEY (KHOA) REFERENCES DONVI(MADV);

ALTER TABLE HOCPHAN
ADD CONSTRAINT FK_HP_DV FOREIGN KEY (MADV) REFERENCES DONVI(MADV);

ALTER TABLE MOMON
ADD CONSTRAINT FK_MM_HP FOREIGN KEY (MAHP) REFERENCES HOCPHAN(MAHP);

ALTER TABLE MOMON
ADD CONSTRAINT FK_MM_GV FOREIGN KEY (MAGV) REFERENCES NHANVIEN(MANLD);

ALTER TABLE DANGKY
ADD CONSTRAINT FK_DK_SV FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV);

ALTER TABLE DANGKY
ADD CONSTRAINT FK_DK_MM FOREIGN KEY (MAMM) REFERENCES MOMON(MAMM);