--TẠO BẢNG DONVI
CREATE TABLE DONVI (
    MADV    VARCHAR2(10) PRIMARY KEY,
    TENDV   VARCHAR2(100) NOT NULL,
    LOAIDV  VARCHAR2(10) CHECK (LOAIDV IN ('Khoa', 'Phòng')),
    TRGDV   VARCHAR2(10)
);

--TẠO BẢNG NHANVIEN
CREATE TABLE NHANVIEN (
    MANLD   VARCHAR2(10) PRIMARY KEY,
    HOTEN   VARCHAR2(100) NOT NULL,
    PHAI    VARCHAR2(5),
    NGSINH  DATE,
    LUONG   NUMBER(10, 2),
    PHUCAP  NUMBER(10, 2),
    DT      VARCHAR2(15),
    VAITRO  VARCHAR2(50),
    MADV    VARCHAR2(10),
    FOREIGN KEY (MADV) REFERENCES DONVI(MADV)
);

--TẠO BẢNG SINHVIEN
CREATE TABLE SINHVIEN (
    MASV       VARCHAR2(10) PRIMARY KEY,
    HOTEN      VARCHAR2(100) NOT NULL,
    PHAI       VARCHAR2(5),
    NGSINH     DATE,
    DCHI       VARCHAR2(200),
    DT         VARCHAR2(15),
    KHOA       VARCHAR2(10),
    TINHTRANG  VARCHAR2(20),
    FOREIGN KEY (KHOA) REFERENCES DONVI(MADV)
);

--TẠO BẢNG HOCPHAN
CREATE TABLE HOCPHAN (
    MAHP   VARCHAR2(10) PRIMARY KEY,
    TENHP  VARCHAR2(100) NOT NULL,
    SOTC   NUMBER(2),
    STLT   NUMBER(3),
    STTH   NUMBER(3),
    MADV   VARCHAR2(10),
    FOREIGN KEY (MADV) REFERENCES DONVI(MADV)
);

--TẠO BẢNG MOMON
CREATE TABLE MOMON (
    MAMM   VARCHAR2(10) PRIMARY KEY,
    MAHP   VARCHAR2(10),
    MAGV   VARCHAR2(10),
    HK     NUMBER(1) CHECK (HK IN (1, 2, 3)),
    NAM    NUMBER(4),
    FOREIGN KEY (MAHP) REFERENCES HOCPHAN(MAHP),
    FOREIGN KEY (MAGV) REFERENCES NHANVIEN(MANLD)
);

--TẠO BẢNG DANGKY
CREATE TABLE DANGKY (
    MASV     VARCHAR2(10),
    MAMM     VARCHAR2(10),
    DIEMTH   NUMBER(4, 2),
    DIEMQT   NUMBER(4, 2),
    DIEMCK   NUMBER(4, 2),
    DIEMTK   NUMBER(4, 2),
    PRIMARY KEY (MASV, MAMM),
    FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV),
    FOREIGN KEY (MAMM) REFERENCES MOMON(MAMM)
);

--THÊM KHÓA NGOẠI CHO BANG DONVI
ALTER TABLE DONVI
ADD CONSTRAINT FK_TRGDV FOREIGN KEY (TRGDV) REFERENCES NHANVIEN(MANLD);