-- Đăng nhập bằng SYS
-- Tạo user quản trị hệ thống ứng dụng
CREATE USER C##ADMIN IDENTIFIED BY 123456 CONTAINER=ALL;

-- Cấp quyền cơ bản
GRANT CONNECT, RESOURCE TO C##ADMIN CONTAINER=ALL;

-- Cấp quyền quản lý user
GRANT CREATE USER TO C##ADMIN CONTAINER=ALL;
GRANT DROP USER TO C##ADMIN CONTAINER=ALL;
GRANT ALTER USER TO C##ADMIN CONTAINER=ALL;

-- Cấp quyền quản lý role (phải do SYS cấp)
GRANT CREATE ROLE TO C##ADMIN CONTAINER=ALL;
GRANT DROP ANY ROLE TO C##ADMIN CONTAINER=ALL;
GRANT GRANT ANY ROLE TO C##ADMIN CONTAINER=ALL;

-- Cấp quyền cấp bất kỳ quyền nào
GRANT GRANT ANY PRIVILEGE TO C##ADMIN CONTAINER=ALL;

-- Cấp quyền xem các user/role/table từ hệ thống
GRANT SELECT_CATALOG_ROLE TO C##ADMIN CONTAINER=ALL;

-- Cấp quyền sử dụng tablespace
GRANT UNLIMITED TABLESPACE TO C##ADMIN CONTAINER=ALL;

GRANT CREATE SESSION TO C##ADMIN CONTAINER=ALL;

GRANT SELECT ANY TABLE TO C##ADMIN CONTAINER=ALL;
GRANT INSERT ANY TABLE TO C##ADMIN CONTAINER=ALL;
GRANT DELETE ANY TABLE TO C##ADMIN CONTAINER=ALL;
GRANT UPDATE ANY TABLE TO C##ADMIN CONTAINER=ALL;

SELECT * 
FROM dba_sys_privs 
WHERE grantee = 'C##ADMIN' 
  AND privilege = 'CREATE USER';

GRANT INHERIT ANY PRIVILEGES TO C##ADMIN CONTAINER=ALL;

GRANT SELECT ON dba_roles TO C##ADMIN CONTAINER=ALL;
GRANT SELECT ON dba_data_files TO C##ADMIN CONTAINER=ALL;

